apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'
group = 'com.cardbuddy.sms'
version = '1.0.0'
android {
  namespace 'com.cardbuddy.sms'
  defaultConfig { minSdkVersion 24 }
  testOptions { unitTests.returnDefaultValues = true }
}
dependencies {
  implementation 'androidx.work:work-runtime-ktx:2.10.1'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.json:json:20240303'
}
